# Generated by Django 3.1.3 on 2020-11-14 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0002_songs'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Songs',
            new_name='Song',
        ),
    ]
