# Generated by Django 3.1.3 on 2020-12-06 16:17

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0007_auto_20201128_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='lyrics',
            field=tinymce.models.HTMLField(),
        ),
    ]
